workspaces:
    workspace_data: "a3a180ff-fbc2-48fd-a65f-27ae7bb6709a"
    workspace_code: "146fe38c-f6c3-4e9d-a18c-5c01cad5941e"
    workspace_config: "f442f66c-eac6-46d7-80c9-c8b025c86fbe"
    workspace_data_prod: "4c4b6bf5-8728-4aac-a132-b008a11b96d7"
    workspace_code_prod: "1284458c-1976-46a6-b9d8-af17c7d11a59"

connections:
    CON_FMD_FABRIC_SQL: "0f86f6a1-9f84-44d1-b977-105b5179c678"
    CON_FMD_FABRIC_PIPELINES: "6b2e33a1-b441-4137-b41d-260ffa8258cf"
    CON_FMD_ADF_PIPELINES: "00000000-0000-0000-0000-000000000000"
    CON_FMD_FABRIC_NOTEBOOKS: "f4d3220c-0cd3-4f76-9641-b4154e192645"

database:
    displayName: "SQL_INTEGRATION_FRAMEWORK"
    id: "501d6b17-fcee-47f3-bbb3-54e05f2a3fc0"
    endpoint: "7xuydsw5a3hutnnj5z2ed72tam-nt3ef5gg5llunagjzcyclsdpxy.database.fabric.microsoft.com,1433"
